### ISSUE TITLE
docker build出现报错问题

### ISSUE THREAD

**Issue by Fredericwu** [jxlwqq/memcached-operator#1]
我跟着你的步骤来做operator，进行到make docker-build的时候出现了一下报错信息，请问你之前有遇到过吗？

![截屏2022-07-06 下午1 57 05](https://user-images.githubusercontent.com/41657047/177485500-649c07ff-9cc9-4165-af49-3dc7bce5cef0.png)

**Comment by jxlwqq** [comment]
可能需要科学上网

**Comment by Fredericwu** [comment]
好的，谢谢

另外问一个问题：你的docker desktop不会有问题吗？  我的macbook air装了docker Desktop能运行，但terminal无法执行docker命令，而且还出现下图的那种报错
![Uploading 截屏2022-07-06 下午3.47.26.png…]()

**Comment by Fredericwu** [comment]
好的，谢谢

另外问一个问题：你的docker desktop不会有问题吗？  我的macbook air装了docker Desktop能运行，但terminal无法执行docker命令，而且还出现下图的那种报错
![截屏2022-07-06 下午3 47 26](https://user-images.githubusercontent.com/41657047/177499535-fbd43e39-20e7-4ab9-ba5f-67d7de56ae22.png)

**Comment by jxlwqq** [comment]
可以重装试试

**Comment by Fredericwu** [comment]
已经重装过多次了，但还是一样。感谢你的解答
